/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    usuarios: Usuario;
    archivos: Archivo;
    categorias: Categoria;
    articulos: Articulo;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    archivos: ArchivosSelect<false> | ArchivosSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    articulos: ArticulosSelect<false> | ArticulosSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    paginas: Pagina;
  };
  globalsSelect: {
    paginas: PaginasSelect<false> | PaginasSelect<true>;
  };
  locale: null;
  user: Usuario & {
    collection: 'usuarios';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: string;
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archivos".
 */
export interface Archivo {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: string;
  title: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articulos".
 */
export interface Articulo {
  id: string;
  title: string;
  subtitle: string;
  slug?: string | null;
  category: string | Categoria;
  content: string;
  imagenes?:
    | {
        imagen: string | Archivo;
        id?: string | null;
      }[]
    | null;
  /**
   * Cambia el estado del post para publicarlo o guardarlo como borrador.
   */
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * La fecha en que el post fue publicado (se establece automáticamente al publicar).
   */
  publishedDate?: string | null;
  author?: (string | null) | Usuario;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'usuarios';
        value: string | Usuario;
      } | null)
    | ({
        relationTo: 'archivos';
        value: string | Archivo;
      } | null)
    | ({
        relationTo: 'categorias';
        value: string | Categoria;
      } | null)
    | ({
        relationTo: 'articulos';
        value: string | Articulo;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: string | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'usuarios';
    value: string | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archivos_select".
 */
export interface ArchivosSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articulos_select".
 */
export interface ArticulosSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  slug?: T;
  category?: T;
  content?: T;
  imagenes?:
    | T
    | {
        imagen?: T;
        id?: T;
      };
  status?: T;
  publishedDate?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: string;
  inicio?: {
    meta?: {
      /**
       * Título para el navegador y motores de búsqueda.
       */
      title?: string | null;
      /**
       * Breve resumen para los motores de búsqueda.
       */
      description?: string | null;
      /**
       * Palabras clave separadas por comas.
       */
      keywords?: string | null;
    };
    inicio?:
      | {
          title: string;
          /**
           * Selecciona los articulos que deseas mostrar en este bloque.
           */
          articulo?:
            | {
                post: string | Articulo;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    contenido?:
      | (
          | {
              heading: string;
              /**
               * Selecciona los articulos que deseas mostrar en este bloque.
               */
              articulo?:
                | {
                    post: string | Articulo;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'detailSideMediaBlock';
            }
          | {
              /**
               * Selecciona los articulos que deseas mostrar en este bloque.
               */
              articulo?:
                | {
                    post: string | Articulo;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'bannerBlock';
            }
          | {
              /**
               * Selecciona los articulos que deseas mostrar en este bloque.
               */
              articulo?:
                | {
                    post: string | Articulo;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'exploreBlock';
            }
          | {
              title: string;
              /**
               * Selecciona los articulos que deseas mostrar en este bloque.
               */
              articulo?:
                | {
                    post: string | Articulo;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'carouselThreeColumns';
            }
          | {
              title: string;
              /**
               * Selecciona los articulos que deseas mostrar en este bloque.
               */
              articulo?:
                | {
                    post: string | Articulo;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'carouselTwoColumns';
            }
          | {
              /**
               * Selecciona los articulos que deseas mostrar en este bloque.
               */
              articulo?:
                | {
                    post: string | Articulo;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'TwoColumns';
            }
        )[]
      | null;
    cierre?:
      | {
          /**
           * Selecciona los articulos que deseas mostrar en este bloque.
           */
          articulo?:
            | {
                post: string | Articulo;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  acerca: {
    introduction?: string | null;
    biography?: string | null;
    phrase?: string | null;
    imageOne: string | Archivo;
    imageTwo: string | Archivo;
    imageThree: string | Archivo;
    imageFour: string | Archivo;
    social?: {
      email?: string | null;
      facebook?: string | null;
      youtube?: string | null;
      tiktok?: string | null;
      twitter?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  inicio?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
              keywords?: T;
            };
        inicio?:
          | T
          | {
              title?: T;
              articulo?:
                | T
                | {
                    post?: T;
                    id?: T;
                  };
              id?: T;
            };
        contenido?:
          | T
          | {
              detailSideMediaBlock?:
                | T
                | {
                    heading?: T;
                    articulo?:
                      | T
                      | {
                          post?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              bannerBlock?:
                | T
                | {
                    articulo?:
                      | T
                      | {
                          post?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              exploreBlock?:
                | T
                | {
                    articulo?:
                      | T
                      | {
                          post?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              carouselThreeColumns?:
                | T
                | {
                    title?: T;
                    articulo?:
                      | T
                      | {
                          post?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              carouselTwoColumns?:
                | T
                | {
                    title?: T;
                    articulo?:
                      | T
                      | {
                          post?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              TwoColumns?:
                | T
                | {
                    articulo?:
                      | T
                      | {
                          post?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        cierre?:
          | T
          | {
              articulo?:
                | T
                | {
                    post?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  acerca?:
    | T
    | {
        introduction?: T;
        biography?: T;
        phrase?: T;
        imageOne?: T;
        imageTwo?: T;
        imageThree?: T;
        imageFour?: T;
        social?:
          | T
          | {
              email?: T;
              facebook?: T;
              youtube?: T;
              tiktok?: T;
              twitter?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}